In [8]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [9]:
tf.random.set_seed(42)

In [10]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [11]:
x_data = np.array([[h]], dtype=np.float32)
x_data

array([[[1., 0., 0., 0.]]], dtype=float32)

In [12]:
x_data.shape #(x, y, z) : x 샘플 갯수, y 토큰 갯수, z 토큰의 임베딩
# x : 일반적으로 문장 1개가 샘플 1개, y : 샘플 1개에서 분해된 token의 개수

(1, 1, 4)

In [13]:
hidden_size = 2
# rnn에 들어갈 cell을 설정
cell = layers.SimpleRNNCell(units=hidden_size) #units로 output_dim = 2로 설정
rnn = layers.RNN(cell, return_sequences=True, return_state=True) 
# rerutn_sequences : 아웃풋 시퀀스의 마지막 아웃풋을 반환할지, 전체를 반환할지 설정
# return_state : 아웃풋에 더해 state를 반환할지
# 이 둘을 True로 주어서 output과 states가 나오는 것

# rnn 입력값 넣기
output, states = rnn(x_data)

print('x_data : {} \t shape : {} '.format(x_data, x_data.shape)) 
print('output : {} \t shape : {} '.format(output, output.shape)) # output과 states의 dim은 같음
print('states : {} \t shape : {}'.format(states, states.shape)) 


x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4) 
output : [[[ 0.31773362 -0.11744198]]] 	 shape : (1, 1, 2) 
states : [[ 0.31773362 -0.11744198]] 	 shape : (1, 2)


In [16]:
hidden_size = 2
# rnn에 들어갈 cell을 설정
cell = layers.SimpleRNNCell(units=hidden_size) #units로 output_dim = 2로 설정
rnn = layers.RNN(cell, return_sequences=True, return_state=False)  # return_state=False로 두어서 states값을 받으려하면 오류가 뜸


# rnn 입력값 넣기
# output, states = rnn(x_data)
output = rnn(x_data)

print('x_data : {} \t shape : {} '.format(x_data, x_data.shape)) 
print('output : {} \t shape : {} '.format(output, output.shape)) # output과 states의 dim은 같음
# print('states : {} \t shape : {}'.format(states, states.shape)) 


x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4) 
output : [[[-0.12818007  0.04968958]]] 	 shape : (1, 1, 2) 


In [17]:
hidden_size = 2
# rnn에 들어갈 cell을 설정
cell = layers.SimpleRNNCell(units=hidden_size) #units로 output_dim = 2로 설정
rnn = layers.RNN(cell, return_sequences=False, return_state=True) 


# rnn 입력값 넣기
output, states = rnn(x_data)

print('x_data : {} \t shape : {} '.format(x_data, x_data.shape)) 
print('output : {} \t shape : {} '.format(output, output.shape)) # output과 states의 dim은 같음
print('states : {} \t shape : {}'.format(states, states.shape)) 


x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4) 
output : [[-0.53046876  0.57137597]] 	 shape : (1, 2) 
states : [[-0.53046876  0.57137597]] 	 shape : (1, 2)


In [18]:
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True) # cell과 모델을 한꺼번에 합친것
output, states = rnn(x_data) # weight는 내부 매커니즘에 따라 랜덤하게 달라지므로 나오는 값들이 매번 다름

print('x_data : {} \t shape : {} '.format(x_data, x_data.shape)) 
print('output : {} \t shape : {} '.format(output, output.shape)) # output과 states의 dim은 같음
print('states : {} \t shape : {}'.format(states, states.shape)) 


x_data : [[[1. 0. 0. 0.]]] 	 shape : (1, 1, 4) 
output : [[[ 0.14876226 -0.53846276]]] 	 shape : (1, 1, 2) 
states : [[ 0.14876226 -0.53846276]] 	 shape : (1, 2)


In [20]:
x_data = np.array([[h,e,l,l,o]],dtype=np.float32)
x_data

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

In [21]:
x_data.shape

(1, 5, 4)

In [22]:
hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {} '.format(x_data, x_data.shape)) 
print('output : {} \t shape : {} '.format(output, output.shape)) # output과 states의 dim은 같음
print('states : {} \t shape : {}'.format(states, states.shape)) 

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]] 	 shape : (1, 5, 4) 
output : [[[ 0.48305762 -0.590541  ]
  [ 0.6646235  -0.47153077]
  [ 0.8331754  -0.38705322]
  [ 0.86460876 -0.50748324]
  [ 0.951724    0.5008572 ]]] 	 shape : (1, 5, 2) 
states : [[0.951724  0.5008572]] 	 shape : (1, 2)


In [23]:
x_data = np.array([[h, e, l, l, o], [e, o, l, l, l], [l, l, e, e, l]], dtype=np.float32)
x_data.shape

(3, 5, 4)

In [25]:
hidden_size = 2
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
output, states = rnn(x_data)

print('x_data : {} \t shape : {} '.format(x_data, x_data.shape)) 
print('output : {} \t shape : {} '.format(output, output.shape)) # output과 states의 dim은 같음
print('states : {} \t shape : {}'.format(states, states.shape)) 

x_data : [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]] 	 shape : (3, 5, 4) 
output : [[[ 0.23709153 -0.28869784]
  [-0.08193244 -0.23037231]
  [-0.48831213  0.30097646]
  [-0.73606753  0.68617874]
  [-0.874941    0.8883536 ]]

 [[-0.30958706  0.05333911]
  [-0.72842443  0.65415514]
  [-0.82840526  0.8315508 ]
  [-0.857429    0.8787449 ]
  [-0.8649625   0.88904196]]

 [[-0.4240446   0.49390674]
  [-0.7054985   0.7754375 ]
  [-0.7730857   0.6786834 ]
  [-0.79878396  0.62288725]
  [-0.8492052   0.82157993]]] 	 shape : (3, 5, 2) 
states : [[-0.874941    0.8883536 ]
 [-0.8649625   0.88904196]
 [-0.8492052   0.82157993]] 	 shape : (3, 2)


In [26]:
idx2char = ['토', '마', '를', '먹', '자']

x_data = [[0, 0, 1, 2, 4, 3]] # 토 토 마 를 자 먹
y_data = [[0, 1, 0, 2, 3, 4]] # 토 마 토 를 먹 자

num_classes = 5
input_dim = 5 
sequence_len = 6 # 토큰의 갯수 # maxlen과 같음
learning_rate = 0.1

x_one_hot = tf.keras.utils.to_categorical(x_data, num_classes=num_classes)
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)

print(x_one_hot)
print(x_one_hot.shape)
print(y_one_hot)
print(y_one_hot.shape)

[[[1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0.]]]
(1, 6, 5)
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]]
(1, 6, 5)


In [33]:
from tensorflow.keras.models import Model

model = tf.keras.Sequential()
cell = layers.SimpleRNNCell(units=num_classes, input_shape=(sequence_len, input_dim))

model.add(layers.RNN(cell=cell, return_sequences=True, return_state=False, input_shape=(sequence_len, input_dim)))
# model.add(layers.SimpleRNN(units=num_classes, return_sequences=True, return_state=False, input_shape=(sequence_len, input_dim)))
model.add(layers.TimeDistributed(layers.Dense(units=num_classes, activation='softmax'))) # output이 나오면 전체에 대해서 계산을 한다는 것 

model.compile(loss='categorical_crossentropy', 
              optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['accuracy'])

model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
rnn_6 (RNN)                  (None, 6, 5)              55        
_________________________________________________________________
time_distributed_2 (TimeDist (None, 6, 5)              30        
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.fit(x_one_hot, y_one_hot, epochs=10)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 1.6266 - accuracy: 0.1667
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 1.2740 - accuracy: 0.6667
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 1.0811 - accuracy: 0.6667
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 0.8655 - accuracy: 0.8333
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 0.7026 - accuracy: 0.8333
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 0.5576 - accuracy: 0.8333
Epoch 7/10
1/1 [==============================] - 0s 18ms/step - loss: 0.4408 - accuracy: 0.8333
Epoch 8/10
1/1 [==============================] - 0s 16ms/step - loss: 0.3515 - accuracy: 0.8333
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 0.2824 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 15ms/step - loss: 0.2260 - accuracy: 1.0000


In [38]:
pred = model.predict(x_one_hot)
pred

array([[[7.0068306e-01, 2.2624083e-01, 4.0264921e-03, 5.3145740e-02,
         1.5903886e-02],
        [2.6606134e-01, 7.0732355e-01, 1.8987456e-02, 1.0663224e-03,
         6.5613077e-03],
        [8.4614211e-01, 1.0278984e-01, 2.1489142e-02, 2.5159881e-02,
         4.4190753e-03],
        [1.6148323e-02, 3.8764288e-03, 9.6223027e-01, 3.8660807e-03,
         1.3878974e-02],
        [5.0204922e-02, 8.2995498e-04, 6.9164927e-03, 9.0479648e-01,
         3.7252154e-02],
        [1.6960142e-02, 1.0499534e-02, 1.2845934e-02, 2.3760075e-02,
         9.3593431e-01]]], dtype=float32)

In [44]:
for i, word in enumerate(pred):
    print(" ".join([idx2char[c] for c in np.argmax(word, axis=1)]))

토 마 토 를 먹 자


In [46]:
!conda freeze

/bin/bash: conda: command not found
