# 데이터 전처리

In [1]:
#레이블인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

#LabelEncoder를 객체로 생선한 후, fir()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 : ', labels) #머신러닝할 시 문자를 알아듣지 못하므로 숫자로 변환

#print('인코딩 클래스 : ', encoder.classes_)
#print('디코딩 원본값 : ', encoder, encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 4, 2]))

인코딩 변환값 :  [0 1 4 5 3 3 2 2]


### One Hot Encoding

In [32]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items) ##숫자로 unique하게 뽑음( Label encoding )
labels = encoder.transform(items)
print("===Label encoding===\n",labels)

# 2차원 데이터로 변환
labels = labels.reshape(-1, 1) #(-1, 1)인 경우와 (-1, 2)인 경우 이해하기, -1인 이유 이해하기
#무조건 (-1, 1)로 해야함
print("===2차원 데이터로 변환된 모양 reshape===\n",labels)

# one-hot encoding 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print("===transform된 oh_labels모양===\n", oh_labels)

print("===원-핫 인코딩 데이터 toarray()===")
print(oh_labels.toarray())#transform되어 나온 출력이 보기어려우므로 보기 쉽게 출력
print("===원-핫 인코딩 데이터 차원(shape)===")
print(oh_labels.shape)

===Label encoding===
 [0 1 4 5 3 3 2 2]
===2차원 데이터로 변환된 모양 reshape===
 [[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]
===transform된 oh_labels모양===
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
===원-핫 인코딩 데이터 toarray()===
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
===원-핫 인코딩 데이터 차원(shape)===
(8, 6)


## One-Hot encoding in Pandas
### pd.get_dummies()

In [30]:
import pandas as pd
df = pd.DataFrame({'items' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

## 피처 스케일링 (feature scaling)
#### x값을 넣기전에 한번 정리하는 것(데이터 전처리)

In [33]:

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print("feature 들의 평균 값")
print(iris_df.mean())
print("\nfeature 들의 분산 값")
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [34]:
#표준화 (Standardization) : StandardScaler
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler 로 데이터 셋 변환, fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transfrom()할 경우 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균 값')
print(iris_df_scaled.mean())
print("\nfeature들의 분산 값")
print(iris_df_scaled.var())

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [36]:
#정규화(Normalization) : Minmax scaler

from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()
# MinMaxScaler로 데이터 셋 변환.fit()과 transform()호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transfrom()할 경우 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최소 값')
print(iris_df_scaled.min())
print("\nfeature들의 최대 값")
print(iris_df_scaled.max())

feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [42]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1, 1)로 차원변경

train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

#최소값 0, 최대값 1로 변환하는 MinMaxScaler객체 생성
scaler = MinMaxScaler()
#fit() 하게 되면 train_array데이터의 최소값이 0, 최대값이 10으로 설정.
scaler.fit(train_array)
# 1/10 scale로 train_array 데이터 변환함. 원본 10 -> 1로 변환됨.
train_scaled = scaler.transform(train_array)

print("원본 train_array데이터", np.round(train_array.reshape(-1), 2))
print("Scale된 train_array데이터:", np.round(train_scaled.reshape(-1), 2))


# 앞에서 생성한 MinMaxScaler에 test_array를 fit()하게 되면 원본데이터의 최소값이0, 최대값이 5로 설정
scaler.fit(test_array)
# 1/5 scale로 test_array데이터 변환함. 원본 5->1로 변환.

test_scaled = scaler.transform(test_array)

print("원본 test_array데이터", np.round(test_array.reshape(-1), 2))
print("Scale된 test_array데이터:", np.round(test_scaled.reshape(-1), 2))

원본 train_array데이터 [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array데이터 [0 1 2 3 4 5]
Scale된 test_array데이터: [0.  0.2 0.4 0.6 0.8 1. ]


## fit을 둘다 하게되면 scale이 달라지므로 fit은 1번만 

In [43]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print("원본 train_array데이터", np.round(train_array.reshape(-1), 2))
print("Scale된 train_array데이터:", np.round(train_scaled.reshape(-1), 2))

#test_array에 Scale변환을 할 때는 반드시 fit()을 호출하지 않고 transform()만으로 변환해야 함.
test_scaled = scaler.transform(test_array)
print("원본 test_array데이터", np.round(test_array.reshape(-1), 2))
print("Scale된 test_array데이터:", np.round(test_scaled.reshape(-1), 2))

원본 train_array데이터 [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array데이터 [0 1 2 3 4 5]
Scale된 test_array데이터: [0.  0.1 0.2 0.3 0.4 0.5]
