# 붓꽃 품종 예측

In [31]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import pandas as pd

### 데이터 준비 및 수집

In [45]:
#붓꽃 데이터 세트 로딩
iris = load_iris()

#iris.data : 피쳐(numpy) ; petal과 sepal의 길이와 넓이 총 4개 ; x값
iris_data = iris.data
print("iris feature값 : \n",iris_data)
print("iris feature명 : \n",iris.feature_names)

#iris.target : 레이블(numpy) ; y값
iris_label = iris.target
print("iris target값 : \n", iris_label)
print("itis target명 : \n", iris.target_names) # 0, 1, 2로 각각의 품종을 구분


iris feature값 : 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5

### train data와  test data 분리

In [46]:
#x에 해당하는 iris_data를 x_train과 x_test로 구분
#y에 해당하는 iris_label를 y_train과 y_test로 구분
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11) 
print(x_train)
print(y_train)
print(x_test)
print(y_test)
#test_size 전체 1 중 0.2 즉 20%만 쓰겠다는 것, random_state 11에 해당하는 규칙대로 랜덤하게 섞는다는 것(seed역할)

[[5.1 3.5 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [7.7 2.8 6.7 2. ]
 [5.  3.3 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [7.6 3.  6.6 2.1]
 [6.7 3.  5.  1.7]
 [5.5 3.5 1.3 0.2]
 [6.  2.7 5.1 1.6]
 [5.  2.  3.5 1. ]
 [7.9 3.8 6.4 2. ]
 [4.6 3.4 1.4 0.3]
 [6.9 3.1 4.9 1.5]
 [6.5 3.  5.8 2.2]
 [5.1 2.5 3.  1.1]
 [6.6 2.9 4.6 1.3]
 [5.  3.2 1.2 0.2]
 [7.4 2.8 6.1 1.9]
 [5.1 3.8 1.6 0.2]
 [6.8 3.2 5.9 2.3]
 [6.9 3.1 5.1 2.3]
 [5.9 3.  4.2 1.5]
 [4.9 2.5 4.5 1.7]
 [6.7 3.1 4.7 1.5]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.7 0.2]
 [6.5 2.8 4.6 1.5]
 [5.1 3.7 1.5 0.4]
 [5.  3.4 1.6 0.4]
 [6.1 2.6 5.6 1.4]
 [6.5 3.  5.5 1.8]
 [6.3 2.5 5.  1.9]
 [5.2 3.4 1.4 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.4 1.5 0.4]
 [6.1 2.8 4.7 1.2]
 [5.1 3.4 1.5 0.2]
 [5.6 3.  4.1 1.3]
 [6.3 2.7 4.9 1.8]
 [7.1 3.  5.9 2.1]
 [5.5 2.6 4.4 1.2]
 [5.  2.3 3.3 1. ]
 [6.3 3.4 5.6 2.4]
 [5.8 2.7 5.1 1.9]
 [5.5 4.2 1.4 0.2]
 [5.6 2.7 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [6.7 2.5 5.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.7 3.1 5.6 2.4]
 [4.6 3.2 1.4 0.2]
 [7.7 3.8 6.

In [47]:
#DecisionTreeClassifier 객체 생성
df_clf = DecisionTreeClassifier(random_state = 11)

#학습 수행
df_clf.fit(x_train, y_train) #구분되어진 x_train은 잎의 넓이와 길이 size가 y_train에는 품종에 해당하는 값인 0, 1, 2가 들어있음

#예측 수행
pred = df_clf.predict(x_test)
#평가 수행
print("예측 정확도 : {0: .4f}".format(accuracy_score(y_test, pred)))

예측 정확도 :  0.9333


In [48]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

pred = dt_clf.predict(train_data)
print(pred)
print("예측 정확도 : ",accuracy_score(train_label, pred))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
예측 정확도 :  1.0


In [53]:
dt_clf = DecisionTreeClassifier()
iris_data = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=12) 

dt_clf.fit(x_train, y_train)
pred = dt_clf.predict(x_test)
print(pred) #훈련된 모델로 x_test를 분류하여 정답지(pred)를 만듦
print("예측 정확도 : {0: .4f}".format(accuracy_score(y_test, pred)))
#데이터의 양이 많지 않기 때문에 정확도가 떨어짐
#=> 데이터 양이 일정수준 이상으로 해야하고 다양한 데이터를 기반으로 테스트가 요구됨

[0 2 0 1 2 2 2 0 2 0 1 0 0 0 1 2 2 1 0 2 0 1 2 1 0 2 2 1 0 0 0 1 2 0 2 0 1
 1 0 1 1 0 0 0 0]
예측 정확도 :  0.9556


## 교차검증  
### K폴드 교차검증

In [251]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

#5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담음
kfold = KFold(n_splits = 5)
cv_accuracy = []

print("붓꽃 데이터 세트 크기 : ", features.shape[0])

붓꽃 데이터 세트 크기 :  150


### Kfold 클래스를 이용하여 붓꽃 데이터 세트를 교차검증

In [252]:
n_iter = 0

#KFold 객체의 split() 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features): ## features = iris.data
                              #kfold = KFold(n_splits = 5) 이미 5개로 쪼갠다고 선언함
    
    #kfold.split()로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터를 추출 
    x_train, x_test = features[train_index], features[test_index] # 150을 5개로 쪼갰으므로 30개씩 반환
    y_train, y_test = label[train_index], label[test_index] ##label = iris.target =>0, 1, 2로 이루어짐
    
    #학습 및 예측
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1
    
    #반복 시 마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = x_train.shape[0] #x_train의 전체 행의 갯수
    test_size = x_test.shape[0] #x_test의 전체 행의 갯수
    
    print("\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}".format(n_iter, accuracy, train_size, test_size) )
    print("#{0} 검증 세트 인덱스 : \n{1}".format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도 : ', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#1 검증 세트 인덱스 : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#2 검증 세트 인덱스 : 
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 : 0.8667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#3 검증 세트 인덱스 : 
[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#4 검증 세트 인덱스 : 
[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 : 0.7333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#5 검증 세트 인덱스 : 
[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도 :  0.9


# Stratified K 폴드
### stratifiedKFond 클래스는 불균형한 분포도를 가진 레이블 데이터 집합을 고려하여 원본 데이터 레이블 분포를 고려한 뒤 데이터 세트를 분배
### KFold의 문제점을 stratifiedKFond클래스로 해결 가능

In [256]:
iris = load_iris()

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [258]:
kfold = KFold(n_splits=3)

n_iter = 0

for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print("## 교차 검증: {0}".format(n_iter))
    print("학습 레이블 데이터 분포:\n", label_train.value_counts())
    print("검증 레이블 데이터 분포:\n", label_test.value_counts()) ##문제 발생 훈련하는 데이터에 없는 데이터로 테스트를 함

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 2    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 1    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [259]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):# skf = StratifiedKFold(n_splits=3) 3개로 쪼개어 교차검증을 3번함
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print("## 교차 검증:{0}".format(n_iter))
    print("학습 레이블 데이터 분포:\n", label_train.value_counts())
    print("검증 레이블 데이터 분포:\n", label_test.value_counts())

## 교차 검증:1
학습 레이블 데이터 분포:
 2    34
1    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
0    17
2    16
Name: label, dtype: int64
## 교차 검증:2
학습 레이블 데이터 분포:
 1    34
2    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    17
0    17
1    16
Name: label, dtype: int64
## 교차 검증:3
학습 레이블 데이터 분포:
 0    34
2    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    17
1    17
0    16
Name: label, dtype: int64


In [260]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
cv_accuracy = []

n_iter = 0


for train_index, test_index in skfold.split(features, label): 

    X_train, X_test = features[train_index], features[test_index] 
    y_train, y_test = label[train_index], label[test_index] 
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0] 
    test_size = X_test.shape[0] 
    
    print("\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}".format(n_iter, accuracy, train_size, test_size) )
    print("#{0} 검증 세트 인덱스 : \n{1}".format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
#교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차검증별 검증 정확도 : ', np.round(cv_accuracy, 4))
print("## 평균 검증 정확도:", np.mean(cv_accuracy)) ##이산적인 데이터에만 사용, 회귀같이 연속데이터에는 사용 불가


#1 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#1 검증 세트 인덱스 : 
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.94, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#2 검증 세트 인덱스 : 
[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#3 검증 세트 인덱스 : 
[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차검증별 검증 정확도 :  [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


### 간편한 교차검증 cross_val_score()

In [261]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

#성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
                                # data = iris_data.data, label = iris_data.target
print('교차 검증별 정확도:', np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


## GridSearchCV : 교차검증 + 하이퍼 파라미터 튜닝
### 하이퍼 파라미터 : 머신러닝을 구성하는 요소, 이를 변경하면서 머신러닝의 성능을 좌우할 수 있음

In [270]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV 
from sklearn.datasets import load_iris

# 데이터를 로딩하고 학습데이터와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

### parameter 들을 dictionary 형태로 설정
parameters = {'max_depth' : [1, 2, 3], 'min_samples_split' : [2, 3]}
              #max_depth 결정 트리의 최대 트리 깊이
                                        #min_samples_splits 자식 규칙 노드를 분할하여 만들기 위한 최소한의 샘플 데이터 개수
import pandas as pd

#param_grid의 하이퍼 파라미터들을 3개의 train, test set fold로 나누어서 테스트 수행
## refit=True가 default임. True이면 가장 좋은 파라미터 설정으로 재 학습 시킴
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True) ##CV:cross validation 교차검증을 의미 cv=3 교차검증을 3번하겠다는 것

# 붓꽃 Train데이터로 param_grid의 하이퍼 파라미터들을 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV결과 추출하여 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_) #grid_dtree.fit(X_train, y_train)의 결과가 cv_results_에 저장됨
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

print('GridSearchCV 최적 파라미터 :', grid_dtree.best_params_)
print("GridSearchCV 최고 정확도: {0: .4f}".format(grid_dtree.best_score_))
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

GridSearchCV 최적 파라미터 : {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:  0.9750


params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [273]:
#GridSearchCV의 refit으로 이미 학습이 된 estimator을 반환
estimator = grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_는 이미 최적 하이퍼 파라미터로 학습이 됨
pred = estimator.predict(X_test)
print("테스트 데이터 세트 정확도: {0: .4f}".format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도:  0.9667
